version: "3.8"

services:
  buzibuddy-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "*********"
    environment:
      - NODE_ENV=production
    restart: always
